spring:
  application:
    name: ledger-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ledger-service}
    username: ${DB_USERNAME:transaction-core}
    password: ${DB_PASSWORD:transaction-core-123}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ledger-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.transactioncore.shared.events
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.transactioncore.shared.events.TransactionInitiatedEvent

server:
  port: ${LEDGER_SERVICE_PORT:8083}

account-service:
  url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info